# Ordinal and One-Hot Encodings for Categorical Data

Author: Jason Brownlee

Article from [machinelearningmastery](https://machinelearningmastery.com/one-hot-encoding-for-categorical-data/).

> Note: In this notebook, I am studying the article mentioned above. Some changes may have been made to the code during its implementation.

# Library

In [31]:
from numpy import asarray
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Ordinal Encoding

## Define data

In [2]:
data = asarray([['red'], ['green'], ['blue']])
print(data)

[['red']
 ['green']
 ['blue']]


## Define ordinal encoding

In [3]:
encoder = OrdinalEncoder()

## Transform data

In [4]:
result = encoder.fit_transform(data)
print(result)

[[2.]
 [1.]
 [0.]]


# One-Hot Encoding

## Define data

In [6]:
data = asarray([['red'], ['green'], ['blue']])
print(data)

[['red']
 ['green']
 ['blue']]


## Define one hot encoding

In [7]:
encoder = OneHotEncoder(sparse=False)

## Transform data

In [8]:
onehot = encoder.fit_transform(data)
print(onehot)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


# Dummy Variable Encoding

## Define data

In [9]:
data = asarray([['red'], ['green'], ['blue']])
print(data)

[['red']
 ['green']
 ['blue']]


## Define one hot encoding


In [10]:
encoder = OneHotEncoder(drop='first', sparse=False)

## Transform data

In [11]:
onehot = encoder.fit_transform(data)
print(onehot)

[[0. 1.]
 [1. 0.]
 [0. 0.]]


# Breast Cancer Dataset

In [15]:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/breast-cancer.csv'
dataset = pd.read_csv(url, header=None)
dataset

0          1        2      3      4    5        6           7  \
0    '40-49'  'premeno'  '15-19'  '0-2'  'yes'  '3'  'right'   'left_up'   
1    '50-59'     'ge40'  '15-19'  '0-2'   'no'  '1'  'right'   'central'   
2    '50-59'     'ge40'  '35-39'  '0-2'   'no'  '2'   'left'  'left_low'   
3    '40-49'  'premeno'  '35-39'  '0-2'  'yes'  '3'  'right'  'left_low'   
4    '40-49'  'premeno'  '30-34'  '3-5'  'yes'  '2'   'left'  'right_up'   
..       ...        ...      ...    ...    ...  ...      ...         ...   
281  '50-59'     'ge40'  '30-34'  '6-8'  'yes'  '2'   'left'  'left_low'   
282  '50-59'  'premeno'  '25-29'  '3-5'  'yes'  '2'   'left'  'left_low'   
283  '30-39'  'premeno'  '30-34'  '6-8'  'yes'  '2'  'right'  'right_up'   
284  '50-59'  'premeno'  '15-19'  '0-2'   'no'  '2'  'right'  'left_low'   
285  '50-59'     'ge40'  '40-44'  '0-2'   'no'  '3'   'left'  'right_up'   

         8                       9  
0     'no'     'recurrence-events'  
1     'no'  'no-recurrence-events'  
2     'no'     'recurrence-events'  
3    'yes'  'no-recurrence-events'  
4     'no'     'recurrence-events'  
..     ...                     ...  
281   'no'  'no-recurrence-events'  
282  'yes'  'no-recurrence-events'  
283   'no'  'no-recurrence-events'  
284   'no'  'no-recurrence-events'  
285   'no'  'no-recurrence-events'  

[286 rows x 10 columns]

## Retrieve the array of data

In [16]:
data = dataset.values

## Separate into input and output columns

In [17]:
X = data[:, :-1].astype(str)
y = data[:, -1].astype(str)

## Summarize

In [18]:
print('Input', X.shape)
print('Output', y.shape)

Input (286, 9)
Output (286,)


## OrdinalEncoder Transform

### Ordinal encode input variables

In [19]:
ordinal_encoder = OrdinalEncoder()
X = ordinal_encoder.fit_transform(X)

### Ordinal encode target variable

In [21]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

### Summarize the transformed data

In [22]:
print('Input', X.shape)
print(X[:5, :])
print('Output', y.shape)
print(y[:5])

Input (286, 9)
[[2. 2. 2. 0. 1. 2. 1. 2. 0.]
 [3. 0. 2. 0. 0. 0. 1. 0. 0.]
 [3. 0. 6. 0. 0. 1. 0. 1. 0.]
 [2. 2. 6. 0. 1. 2. 1. 1. 1.]
 [2. 2. 5. 4. 1. 1. 0. 4. 0.]]
Output (286,)
[1 0 1 0 1]


### Split the dataset into train and test sets

In [24]:
X = data[:, :-1].astype(str)
y = data[:, -1].astype(str)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

### Ordinal encode input variables

In [25]:
ordinal_encoder = OrdinalEncoder()
ordinal_encoder.fit(X_train)
X_train = ordinal_encoder.transform(X_train)
X_test = ordinal_encoder.transform(X_test)

### Ordinal encode target variable

In [26]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
y_train = label_encoder.transform(y_train)
y_test = label_encoder.transform(y_test)

### Define the model

In [28]:
model = LogisticRegression()

### Fit on the training set

In [29]:
model.fit(X_train, y_train)

LogisticRegression()

### Predict on test set

In [30]:
yhat = model.predict(X_test)

### Evaluate predictions

In [32]:
accuracy = accuracy_score(y_test, yhat)
print('Accyracy: %.2f' % (accuracy*100))

Accyracy: 75.79


## OneHotEncoder Transform

### One hot encode input variables

In [34]:
X = data[:, :-1].astype(str)
y = data[:, -1].astype(str)

onehot_encoder = OneHotEncoder(sparse=False)
X = onehot_encoder.fit_transform(X)
X

array([[0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

### Ordinal encode target variable

In [36]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Summarize the transformed data

In [37]:
print('Input', X.shape)
print(X[:5, :])

Input (286, 43)
[[0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0.]]


### split the dataset into train and test sets


In [38]:
X = data[:, :-1].astype(str)
y = data[:, -1].astype(str)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

### One-hot encode input variables

In [39]:
onehot_encoder = OneHotEncoder()
onehot_encoder.fit(X_train)
X_train = onehot_encoder.transform(X_train)
X_test = onehot_encoder.transform(X_test)

### ordinal encode target variable

In [40]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
y_train = label_encoder.transform(y_train)
y_test = label_encoder.transform(y_test)

### Define the model

In [41]:
model = LogisticRegression()

### Fit on the training set

In [42]:
model.fit(X_train, y_train)

LogisticRegression()

### Predict on test set

In [43]:
yhat = model.predict(X_test)

### Evaluate predictions

In [44]:
accuracy = accuracy_score(y_test, yhat)
print('Accuracy: %.2f' % (accuracy*100))

Accuracy: 70.53
